language: ruby
rvm:
- 2.5
- 2.6
gemfile:
- gemfiles/Gemfile.rails52
- gemfiles/Gemfile.rails60
sudo: false
cache: bundler
before_script: bundle update
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake test
notifications:
  slack:
    on_pull_requests: false
    on_success: always
    on_failure: always
    rooms:
      secure: buz9fL78yLJZNuYNt5upZyXJesDqSsRqQzBfyxQjmy2t22WFlRBBPZUtiCpcAw4CJiTlyZqEKihxYdpcn26EdRGv5mG/R+POy4xAVap+I1jgWHbgbN9cLW6cPcDgirxD6UWP0Cskt+L9VcAyS9tSNCzjLOne113PPKr82BO5mcfFobF4iWVTsXntgwLxCfl/lsuSm0w2/lzOyFgqkTC3xq78e1C5m6XKlm2brf9TFu2sT2S05xZzBBYsloJXChUeUf5PA9cQdDLfvlJVVn2tYkm4mh6nHQXUczCtU1XL8AKGWHBnFEZ2aHWmVBvWGCKCFwQrbs5ipOH1U76xXQ9iomOerj4kWBITW9p9arxW3ydxu03gV4a5xTKMn+4ISyFmyrEz7GDmT6ER/ymAuSOb82TMTSN6GgepgRPImIiVij8uU86OrUzavvdA1XhVq0NU8c3g3+b/8MDD219crSgbWqaQjnzllfE3T1ldaKII9/xsCk1Ewz8a8Y1XkPqxDHY8lAq6NAB67dV99pwxASQ+7hIu07k9ZJNBOnP3Bt4xZHSVx4ni/0Iv99XeaSBkI4hp2nEYJB61or9B7By8H+x3Zn7m+rftYJpxSbkDwnXQYhn1nkRG+G2lnVxTde3tjUwKDa9gl+eEQAG9g9Jw6FIyhYUxRGpPkWosUmpGJZy3P7g=
