language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - gemfiles/Gemfile.rails42
  - gemfiles/Gemfile.rails50
  - gemfiles/Gemfile.rails51

sudo: false

cache: bundler

before_script: "bundle update"

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test

notifications:
  slack:
    secure: rBle/mKAbEQ2lcCbxJ5mnph8YGttApzP/MrYNeCfY8G6Do4gbG4Vwd29JxABvZ8DIonBa9Qd6loW9xoUi4DSaaUUB205/4KGivp42RTZW2zyln8uMS1PZglZZuhu/0lUcKKOOj/DP+ITOs8UqgSVhf9t7dihF4XNXhq0sd0wsK5qNFdoYENILr/Cb4jI+Lqwk2JOtONC+LjUc2WqvIFp0YYU9XNWsh9nulEmRHU8piqY5dzxOk93TwIr6rtPGaphgEFkNe1JHbKWrQ4HwQq9vRrKPOX1K0U2x3sNFWufprB5d9ik1YEdSCTKm20Wa8TzoMKXEkWKDygYPkvntGF2GmZXliF/CLWC1hixCb/PhyvuluuYTAeIN6JobZDMyo+CFoEHkYjiY/TRIj9kXCEaQMN6T/Ccvxi7quFWHtxBloSRqtjN6Oqn60Niu3RdRiHKPv5uIjKCY3+lF+KJ6v8+7qzM7ETNlWeipMBH+4eMTqNqoBLX3QJUzJOZUHUpDFFg+GnYM2WFMv4LV3QNX6UU3631YwiQDgu06BnhHZba840Zhsu8z2p6KZ+sejaEVCsvfFS1y71plvZIGoeZGjX8JCZfSs+SW76i42a5pgOeFKAVUD8UCxGWGAoh//Iu3OQzv1cbq/7F1v64OL13ugNY9DQyWr8iCpqO8yKww3qNTnM=
    on_pull_requests: false
