language: ruby

rvm:
  - 1.9.3
  - 2.3

gemfile:
  - gemfiles/Gemfile.rails32

sudo: false

cache: bundler

before_script: "bundle update"

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test
