language: ruby

rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1

gemfile:
  - gemfiles/Gemfile.rails32
  - gemfiles/Gemfile.rails41
  - gemfiles/Gemfile.rails42
  - gemfiles/Gemfile.rails50

matrix:
  exclude:
    - rvm: 2.1.9
      gemfile: gemfiles/Gemfile.rails50

sudo: false

cache: bundler

before_script: "bundle update"

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake test
  - bundle exec rubocop .
